### ISSUE TITLE
Game crashs on load

### ISSUE THREAD

**Issue by slottwo** [wildcardgamez/Buddycards-Expansions#1]
Error Screen:
![Captura de tela de 2022-07-18 10-21-57](https://user-images.githubusercontent.com/41028091/179790942-53f80070-26b9-4b20-ba7a-f6781401c8f7.png)

Crash Log:
[crash-2022-07-18_10.19.13-fml.txt](https://github.com/wildcardgamez/Buddycards-Expansions/files/9142594/crash-2022-07-18_10.19.13-fml.txt)

**Comment by slottwo** [comment]
Correction, I'm testing and some mods on 1.18.2 with _Forge 40.1.60_  just don't work, I'm now deleting `.minecraft` and reinstalling minecraft to understand the problem, because even with just the mods _Buddycards Expansion 1.0.4_, _Buddycars 3.1.1_ and _Curios API_ the error occurs.

**Comment by slottwo** [comment]
Mods:
![image](https://user-images.githubusercontent.com/41028091/179838365-b7f08473-a262-4b6e-93f7-52c6a3ecd192.png)

Crash screen:
![image](https://user-images.githubusercontent.com/41028091/179838510-aa9e9912-d91f-4661-9a51-85ace70202b5.png)

Crash Log:
[crash-2022-07-19_17.04.19-fml.txt](https://github.com/wildcardgamez/Buddycards-Expansions/files/9144316/crash-2022-07-19_17.04.19-fml.txt)

**Comment by slottwo** [comment]
Java Version:
![image](https://user-images.githubusercontent.com/41028091/179838961-35cafe70-c9de-4ec5-901c-74c6066fcc11.png)

System Details:
![image](https://user-images.githubusercontent.com/41028091/179839132-339224cc-91a3-4a51-9c42-ce4ab9391a27.png)

**Comment by RedstoneFox** [comment]
Uh... I don't mean to be that guy... but the mod is for 1.18.1 and hasn't been updated yet to 1.18.2...

**Comment by slottwo** [comment]
Oh... Sorry, I didn't realize that. 😆 (Extremely embarrassed laughter)

**Comment by wildcardgamez** [comment]
Yeah, it currently isn't made for the latest version
