### ISSUE TITLE
Create 0.5.1 Crash

### ISSUE THREAD

**Issue by NightmareTwilight** [wildcardgamez/Buddycards-Expansions#10]
With the new update to Create some behind the scene stuff seems to have changed, which requires updating. As it is now, the latest version (1.1.4) does not work with Create v0.5.1.

**Comment by wildcardgamez** [comment]
Malum also has some issues. The expansions mod is a mess right now. I'll leave this here for when we get around to updating expansions.

**Comment by wildcardgamez** [comment]
Fixed in current version (and one before it because I forgot to close this)
