### ISSUE TITLE
(1.16.5) Rattat Card has two stray pixels

### ISSUE THREAD

**Issue by NARbluebear** [wildcardgamez/Buddycards-Expansions#11]
This isn't a major issue, but while I was opening some Mystery Packs in the Create: Above and Beyond modpack, I noticed that the Rattat card (`buddycards:card.7.16`) has two stray pixels on the left side.
Screenshot:
![image](https://github.com/wildcardgamez/Buddycards-Expansions/assets/31386797/7c25699f-6819-49a8-a089-c890fe3b48bd)
Texture:
![card 7 16](https://github.com/wildcardgamez/Buddycards-Expansions/assets/31386797/f5f3322f-db56-4a1a-a4ee-d1ca76a7da08)
I went ahead and dug through the repo, and it does not seem like the pixels are actually in [the sprite uploaded here](https://github.com/wildcardgamez/Buddycards-Expansions/blob/main/src/main/resources/assets/buddycardsexp/textures/item/farmers_set/16.png). If the 1.16.5 version's still being updated, I would like to see this fixed. If not, that's fine as I probably won't stare at the cards for too long when storing them.

**Comment by wildcardgamez** [comment]
Wrong repo, but the repository for Buddycards 1.16.5 which this would be for has been archived. This is the 1.18 Buddycards expansions mod, which as you stated doesn't have the same issue.
