### ISSUE TITLE
startup issue

### ISSUE THREAD

**Issue by Rosenblack** [wildcardgamez/Buddycards-Expansions#2]
no matter what i do i cant get the expansion to work with the mods ive got, too many of them have to be disabled in order for this to work properly, any idea whats up?
[error.txt](https://github.com/wildcardgamez/Buddycards-Expansions/files/9420723/error.txt)

**Comment by wildcardgamez** [comment]
This is a forge issue iirc, and has to do with drivers I think? Its an
issue in the newer versions of forge. I dont know much about it.

**Comment by Rosenblack** [comment]
ah fair, i mod for fabric so forges logs are a bit alien to me, ill do some more tinkering if it is an issue on my end, thank you

**Comment by wildcardgamez** [comment]
I dont know why certain things dont load, ill look into it eventually. As
long as the mods are there, all of the content shouldve loaded. Please make
sure you are running with all 6 required mods. Let me know of that fixes
anything. I have no idea how to recreate this or what the issue is

**Comment by wildcardgamez** [comment]
https://github.com/wildcardgamez/Buddycards-Expansions/commit/fe973ce3e08d6675a6aa2c86019f336748634b55
Small patch just happened, can you try 1.1.1 and see if that fixes this? It fixes some other crashes but I don't really know what causes the issue you have

**Comment by Rosenblack** [comment]
before your update, i did what i could, turns out that particular error is a nvidia issue, somehow your mod made it so i couldnt have more than 192 mods or my graphics card died, its a gtx 970 so not new, BUUUUUUT that being said, update has _seemed_ to have fixed it, so thank you <3
