### ISSUE TITLE
Typos and Possible missing texture

### ISSUE THREAD

**Issue by Rosenblack** [wildcardgamez/Buddycards-Expansions#5]
so just to state, i am using a texture pack to up the card sizes but ive basically removed every other texture from it so using base textures minus card sprites, the buddy hook on my iron aquaculture 2 rod shows a missing texture, it might be the bobber tho? since they take up the same space but thats base too? and im new to that mod so unsure if you render the hook or not, sorry if not.

possible typos in the create set, andesite is spelt adnesite, the others that look odd to me seem to be spell interestingly for added character but ye, at least one typo

**Comment by wildcardgamez** [comment]
Typos are on purpose. And the bobber will be fixed soon. Dont know about
the rest of it sounds like a personal issue.

**Comment by Rosenblack** [comment]
sweet, thanks

**Comment by wildcardgamez** [comment]
Fixed
https://github.com/wildcardgamez/Buddycards-Expansions/commit/2175a821f6bc5f2b9538b85232f32260891ca743
