### ISSUE TITLE
incompatible with latest malum update

### ISSUE THREAD

**Issue by Rosenblack** [wildcardgamez/Buddycards-Expansions#6]
![Screenshot_1](https://user-images.githubusercontent.com/10399357/189182651-6a97e033-c4fe-412b-a590-66729c0d94ea.png)

**Comment by DelviousCrafts** [comment]
I was coming here to report as well.

[crash report](https://github.com/wildcardgamez/Buddycards-Expansions/files/10459969/crash-2023-01-19_11.24.59-fml.txt) for assistance in fixing

Versions: 
Minecraft: 1.18.2
Forge: 40.2.0
Lodestone: 1.3
Buddycards: 3.2.1
Malum: 1.4.4
Buddycards Expansion: 1.1.4
